// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdiMnVLE4aD_LcAM3ldOgHUQV1og4cqt4',
    appId: '1:851544109537:web:7171c5156206d3415ba2a0',
    messagingSenderId: '851544109537',
    projectId: 'mentora-fd18a',
    authDomain: 'mentora-fd18a.firebaseapp.com',
    storageBucket: 'mentora-fd18a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9UYYwNTGkPGp0C6RMqEpl6RPaPkgZ_uA',
    appId: '1:851544109537:android:4e77635e2ccd1aca5ba2a0',
    messagingSenderId: '851544109537',
    projectId: 'mentora-fd18a',
    storageBucket: 'mentora-fd18a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoNiQSxMcgMobAZi24hWHN6gqUUewm0hE',
    appId: '1:851544109537:ios:8e3d3eea177139ce5ba2a0',
    messagingSenderId: '851544109537',
    projectId: 'mentora-fd18a',
    storageBucket: 'mentora-fd18a.firebasestorage.app',
    iosBundleId: 'com.example.mentoraapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoNiQSxMcgMobAZi24hWHN6gqUUewm0hE',
    appId: '1:851544109537:ios:8e3d3eea177139ce5ba2a0',
    messagingSenderId: '851544109537',
    projectId: 'mentora-fd18a',
    storageBucket: 'mentora-fd18a.firebasestorage.app',
    iosBundleId: 'com.example.mentoraapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdiMnVLE4aD_LcAM3ldOgHUQV1og4cqt4',
    appId: '1:851544109537:web:9291b4212cf916275ba2a0',
    messagingSenderId: '851544109537',
    projectId: 'mentora-fd18a',
    authDomain: 'mentora-fd18a.firebaseapp.com',
    storageBucket: 'mentora-fd18a.firebasestorage.app',
  );

}